version: "3"
services:
  db:
    image: postgres
    container_name: webserver
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "minseo"
      POSTGRES_PASSWORD: "minseo"
      POSTGRES_DB: "foodie"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C"
    volumes:
      - "./data/:/var/lib/postgresql/data"
      - "./init/:/docker-entrypoint-initdb.d"
